version: '3'

services:
  xui:
    # 镜像名称
    image: adams549659584/x-ui:latest
    # 容器名称
    container_name: x-ui
    # 设定上下文根目录，然后以该目录为准指定 Dockerfile，赋值Dockerfile 中的 ARG 指令
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # 自启动
    restart: unless-stopped
    # 加入指定网络
    # networks:
    #   - MyNetwork
    network_mode: host
    environment:
      XUI_WEB_PORT: 54322
    volumes:
      - ./db:/etc/x-ui

# networks:
#   MyNetwork:
#   # bridge-host:
#     external: true

